// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpqszeopburoownkweav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwcXN6ZW9wYnVyb293bmt3ZWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NTIyODgsImV4cCI6MjA3NjEyODI4OH0.DAWEJRTZx76mGwraXa5BuRYLZN-kUzDqtDFfa4Nx-XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});